openapi: 3.0.1
info:
  title: Products Service API
  description: API for managing products
  version: 1.0.0
servers:
  - url: https://de01ziaid1.execute-api.eu-north-1.amazonaws.com/prod

components:
  schemas:
    Product:
      type: object
      properties:
        id:
          type: string
        title:
          type: string
        description:
          type: string
        price:
          type: number
        count:
          type: number

paths:
  /products:
    get:
      summary: Get list of products
      responses:
        '200':
          description: Returns a list of products
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Product'
        '500':
          description: Can't fetch products list
    post:
      summary: Creates a product
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                title:
                  type: string
                description:
                  type: string
                price:
                  type: number
                count:
                  type: number
              required:
                - title
                - price
                - count
                - description
      responses:
        '201':
          description: Product created
        '400':
          description: Invalid request body
        '500':
          description: Product can't be created

  /products/{productId}:
    get:
      summary: Get product by ID
      parameters:
        - name: productId
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Returns product with given ID
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Product'
        '404':
          description: Product not found
