openapi: 3.1.0
info:
  title: Products Service API
  description: API for managing products
  version: 1.0.0
servers:
  - url: https://de01ziaid1.execute-api.eu-north-1.amazonaws.com/prod

paths:
  /products:
    get:
      summary: Get list of products
      responses:
        '200':
            description: Returns a list of products
            content:
              application/json:
                schema:
                  type: array
                  items:
                    type: object
                    properties:
                      id:
                        type: string
                      title:
                        type: string
                      description:
                        type: string
                      price:
                        type: number

  /products/{productId}:
    get:
      summary: Get product by ID
      parameters:
         name: id
        in: path
        required: true
        schema:
          type: string
      responses:
        '200':
          description: Returns product with given ID
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: string
                  title:
                    type: string
                  description:
                    type: string
                  price:
                    type: number
        '404':
          description: Product not found

                      